import { add, compare, conditional, divide, literal, max, multiply, ref, subtract, sum } from './ast';
import type {
  FormulaSpec,
  Grain,
  InputConfig,
  KnowledgeStatus,
  MetricBehavior,
  MetricDef,
  MetricDomain,
  MetricKind,
  MetricRole,
  ModelState,
  Provenance,
  UnitSpec,
} from './model';
import { MODEL_SCHEMA_VERSION } from './model';
import {
  CYCLE,
  CYCLE_PER_POWERBANK,
  CYCLE_PER_RENTAL,
  DAY,
  DIMENSIONLESS,
  MONTH,
  PERCENT,
  POWERBANK,
  RENTAL,
  RENTAL_PER_DAY,
  RUB,
  RUB_PER_POWERBANK,
  RUB_PER_RENTAL,
  SLOT,
} from './units';

const stationMonth: Grain = { entity: 'station', time: 'month' };
const stationSnapshot: Grain = { entity: 'station', time: 'none' };

const workbookProvenance: Provenance = {
  source: 'tokberi_unit_economics_model.numbers',
  version: 'working-draft-2026-07-18',
  confidence: 'medium',
  comment: 'Рабочее допущение из исходной модели; франшиза и HQ исключены.',
};

const tariffProvenance: Provenance = {
  source: 'tokberi_unit_economics_model.numbers',
  version: 'tariff-working-v1',
  confidence: 'medium',
  comment: 'Тариф требует сверки с актуальной продуктовой конфигурацией.',
};

const engineProvenance: Provenance = {
  source: 'EconomicSimulator formula',
  version: 'schema-v1',
  confidence: 'high',
};

interface MetricOptions {
  id: string;
  name: string;
  description: string;
  behavior: MetricBehavior;
  unit: UnitSpec;
  kind?: MetricKind;
  value?: number | null;
  formula?: FormulaSpec;
  domain: MetricDomain;
  role: MetricRole;
  knowledgeStatus?: KnowledgeStatus;
  grain?: Grain;
  provenance?: Provenance;
  inputConfig?: InputConfig;
  position: { x: number; y: number };
}

function metric(options: MetricOptions): MetricDef {
  const kind = options.kind ?? (options.formula ? 'derived' : 'assumption');
  return {
    id: options.id,
    definitionId: `tokberi.${options.id}`,
    name: options.name,
    description: options.description,
    behavior: options.behavior,
    unit: options.unit,
    grain: options.grain ?? stationMonth,
    valueSource: kind === 'derived' ? 'derived' : kind === 'observed' ? 'observed' : 'input',
    knowledgeStatus: options.knowledgeStatus ?? (kind === 'derived' ? 'derived' : 'assumption'),
    kind,
    domain: options.domain,
    role: options.role,
    value: options.value ?? null,
    formula: options.formula,
    provenance: options.provenance ?? (kind === 'derived' ? engineProvenance : workbookProvenance),
    validationStatus: options.formula || options.value !== null ? 'valid' : 'incomplete',
    validationMessages: [],
    position: options.position,
    inputConfig: options.inputConfig,
  };
}

function formula(source: string, ast: FormulaSpec['ast']): FormulaSpec {
  return { source, ast };
}

function input(
  id: string,
  name: string,
  description: string,
  behavior: MetricBehavior,
  unit: UnitSpec,
  value: number,
  domain: MetricDomain,
  role: MetricRole,
  position: { x: number; y: number },
  inputConfig: InputConfig,
  options: Partial<Pick<MetricOptions, 'grain' | 'provenance' | 'knowledgeStatus' | 'kind'>> = {},
): MetricDef {
  return metric({
    id,
    name,
    description,
    behavior,
    unit,
    value,
    domain,
    role,
    position,
    inputConfig,
    ...options,
  });
}

export function createTokBeriModel(): ModelState {
  const metricList: MetricDef[] = [
    input(
      'potential_demand',
      'Потенциальный спрос',
      'Оценка доступного спроса на одну станцию в день. Это guardrail, а не скрытый cap.',
      'rate',
      RENTAL_PER_DAY,
      1.7,
      'demand',
      'driver',
      { x: 60, y: 60 },
      { min: 0, max: 30, step: 0.1 },
    ),
    input(
      'rentals_per_day',
      'Аренд в день',
      'Моделируемое число успешных аренд на одну станцию в день.',
      'rate',
      RENTAL_PER_DAY,
      1.5,
      'demand',
      'input',
      { x: 60, y: 190 },
      { min: 0, max: 30, step: 0.1 },
    ),
    input(
      'operational_capacity',
      'Операционная capacity',
      'Максимальная реалистичная пропускная способность станции в день.',
      'rate',
      RENTAL_PER_DAY,
      6,
      'operations',
      'constraint',
      { x: 60, y: 320 },
      { min: 0.5, max: 40, step: 0.5 },
    ),
    input(
      'total_slots',
      'Слотов в станции',
      'Физическая ёмкость станции.',
      'stock',
      SLOT,
      6,
      'operations',
      'constraint',
      { x: 60, y: 450 },
      { min: 4, max: 48, step: 1, integer: true },
      { grain: stationSnapshot },
    ),
    input(
      'battery_count',
      'Батарей в станции',
      'Стартовое целое количество пауэрбанков, купленных для станции.',
      'stock',
      POWERBANK,
      4,
      'capex',
      'input',
      { x: 60, y: 580 },
      { min: 1, max: 48, step: 1, integer: true },
      { grain: stationSnapshot },
    ),
    input(
      'minimum_free_slots',
      'Минимум свободных слотов',
      'Операционный запас свободных слотов для возврата батарей.',
      'stock',
      SLOT,
      1,
      'operations',
      'guardrail',
      { x: 60, y: 710 },
      { min: 1, max: 8, step: 1, integer: true },
      { grain: stationSnapshot },
    ),
    input(
      'short_tariff_share',
      'Доля короткого тарифа',
      'Доля аренд с коротким тарифом. Внутри движка хранится от 0 до 1.',
      'rate',
      PERCENT,
      0.8,
      'revenue',
      'driver',
      { x: 60, y: 840 },
      { min: 0, max: 1, step: 0.01 },
      { provenance: tariffProvenance },
    ),
    input(
      'short_tariff_check',
      'Чек короткого тарифа',
      'Среднее успешное списание для короткого сценария аренды.',
      'rate',
      RUB_PER_RENTAL,
      200,
      'revenue',
      'driver',
      { x: 60, y: 970 },
      { min: 0, max: 1500, step: 10 },
      { provenance: tariffProvenance },
    ),
    input(
      'long_tariff_check',
      'Чек длинного тарифа',
      'Среднее успешное списание для длинного сценария аренды.',
      'rate',
      RUB_PER_RENTAL,
      435,
      'revenue',
      'driver',
      { x: 60, y: 1100 },
      { min: 0, max: 3000, step: 5 },
      { provenance: tariffProvenance },
    ),
    input(
      'deposit_amount',
      'Депозит',
      'Справочная сумма депозита. Она намеренно не входит в арендную выручку.',
      'rate',
      RUB_PER_POWERBANK,
      500,
      'revenue',
      'diagnostic',
      { x: 60, y: 1230 },
      { min: 0, max: 5000, step: 100 },
      { provenance: tariffProvenance },
    ),

    metric({
      id: 'successful_rentals',
      name: 'Успешные аренды за месяц',
      description: 'Только состоявшиеся аренды за 30-дневный модельный период.',
      behavior: 'flow',
      unit: RENTAL,
      formula: formula('rentals_per_day × 30 days', multiply(ref('rentals_per_day'), literal(30, DAY))),
      domain: 'demand',
      role: 'output',
      position: { x: 420, y: 100 },
    }),
    metric({
      id: 'capacity_utilization',
      name: 'Загрузка capacity',
      description: 'Доля заявленного операционного лимита.',
      behavior: 'rate',
      unit: DIMENSIONLESS,
      formula: formula('rentals_per_day / operational_capacity', divide(ref('rentals_per_day'), ref('operational_capacity'))),
      domain: 'operations',
      role: 'guardrail',
      position: { x: 420, y: 230 },
    }),
    metric({
      id: 'average_check',
      name: 'Средний чек',
      description: 'Взвешенный средний чек по тарифному миксу.',
      behavior: 'rate',
      unit: RUB_PER_RENTAL,
      formula: formula(
        'short_check × short_share + long_check × (1 − short_share)',
        add(
          multiply(ref('short_tariff_check'), ref('short_tariff_share')),
          multiply(ref('long_tariff_check'), subtract(literal(1), ref('short_tariff_share'))),
        ),
      ),
      domain: 'revenue',
      role: 'driver',
      position: { x: 420, y: 360 },
    }),
    metric({
      id: 'rental_revenue',
      name: 'Арендная выручка',
      description: 'Только успешные арендные списания; депозит сюда не входит.',
      behavior: 'flow',
      unit: RUB,
      formula: formula('successful_rentals × average_check', multiply(ref('successful_rentals'), ref('average_check'))),
      domain: 'revenue',
      role: 'output',
      position: { x: 780, y: 100 },
    }),

    input(
      'venue_commission_rate',
      'Комиссия площадке',
      'Доля арендной выручки, выплачиваемая партнёрской локации.',
      'rate',
      PERCENT,
      0.2,
      'variable_costs',
      'driver',
      { x: 420, y: 520 },
      { min: 0, max: 0.6, step: 0.01 },
    ),
    input(
      'acquiring_rate',
      'Эквайринг',
      'Комиссия платёжного провайдера от успешной арендной выручки.',
      'rate',
      PERCENT,
      0.035,
      'variable_costs',
      'driver',
      { x: 420, y: 650 },
      { min: 0, max: 0.15, step: 0.001 },
    ),
    input(
      'loss_reserve_rate',
      'Резерв на потери',
      'Упрощённый резерв от выручки, пока фактических событий потери нет.',
      'rate',
      PERCENT,
      0.05,
      'variable_costs',
      'driver',
      { x: 420, y: 780 },
      { min: 0, max: 0.3, step: 0.005 },
    ),
    input(
      'use_event_loss_data',
      'Использовать факт потерь',
      '0 — сценарный резерв, 1 — lost units и взысканное возмещение.',
      'rate',
      DIMENSIONLESS,
      0,
      'variable_costs',
      'input',
      { x: 420, y: 910 },
      { min: 0, max: 1, step: 1, integer: true },
    ),
    input(
      'lost_units',
      'Потеряно батарей',
      'Число подтверждённых событий потери за месяц.',
      'flow',
      POWERBANK,
      0,
      'variable_costs',
      'input',
      { x: 420, y: 1040 },
      { min: 0, max: 30, step: 1, integer: true },
    ),
    input(
      'recovered_lost_charge',
      'Взыскано за потери',
      'Подтверждённый денежный поток возмещения; отдельно от rental revenue.',
      'flow',
      RUB,
      0,
      'revenue',
      'input',
      { x: 420, y: 1170 },
      { min: 0, max: 30000, step: 100 },
    ),
    input(
      'loss_handling_cost',
      'Обработка потерь',
      'Дополнительные затраты на подтверждённые события потери за месяц.',
      'flow',
      RUB,
      0,
      'variable_costs',
      'input',
      { x: 420, y: 1300 },
      { min: 0, max: 30000, step: 100 },
    ),
    input(
      'battery_replacement_cost',
      'Стоимость батареи',
      'Цена замены одной батареи.',
      'rate',
      RUB_PER_POWERBANK,
      1200,
      'capex',
      'driver',
      { x: 420, y: 1430 },
      { min: 0, max: 10000, step: 100 },
      { grain: stationSnapshot },
    ),
    input(
      'cycles_per_rental',
      'Циклов на аренду',
      'Среднее число эквивалентных циклов батареи на завершённую аренду.',
      'rate',
      CYCLE_PER_RENTAL,
      1,
      'variable_costs',
      'driver',
      { x: 420, y: 1560 },
      { min: 0.1, max: 3, step: 0.1 },
    ),
    input(
      'useful_cycles_per_battery',
      'Ресурс батареи',
      'Рабочее допущение по числу полезных циклов до замены.',
      'rate',
      CYCLE_PER_POWERBANK,
      600,
      'variable_costs',
      'driver',
      { x: 420, y: 1690 },
      { min: 50, max: 2000, step: 50 },
    ),

    metric({
      id: 'venue_commission',
      name: 'Расход: площадка',
      description: 'Комиссия партнёрской локации.',
      behavior: 'flow',
      unit: RUB,
      formula: formula('rental_revenue × venue_commission_rate', multiply(ref('rental_revenue'), ref('venue_commission_rate'))),
      domain: 'variable_costs',
      role: 'intermediate',
      position: { x: 780, y: 250 },
    }),
    metric({
      id: 'acquiring_cost',
      name: 'Расход: эквайринг',
      description: 'Комиссия платёжного провайдера.',
      behavior: 'flow',
      unit: RUB,
      formula: formula('rental_revenue × acquiring_rate', multiply(ref('rental_revenue'), ref('acquiring_rate'))),
      domain: 'variable_costs',
      role: 'intermediate',
      position: { x: 780, y: 380 },
    }),
    metric({
      id: 'loss_reserve_cost',
      name: 'Сценарный резерв потерь',
      description: 'Упрощённый резерв в режиме без фактических событий.',
      behavior: 'flow',
      unit: RUB,
      formula: formula('rental_revenue × loss_reserve_rate', multiply(ref('rental_revenue'), ref('loss_reserve_rate'))),
      domain: 'variable_costs',
      role: 'intermediate',
      position: { x: 780, y: 510 },
    }),
    metric({
      id: 'event_loss_cost',
      name: 'Фактическая стоимость потерь',
      description: 'lost units × replacement + handling − recovered charge, не ниже нуля.',
      behavior: 'flow',
      unit: RUB,
      formula: formula(
        'max(lost_units × replacement_cost + handling − recovered_charge, 0)',
        max(
          subtract(
            add(multiply(ref('lost_units'), ref('battery_replacement_cost')), ref('loss_handling_cost')),
            ref('recovered_lost_charge'),
          ),
          literal(0),
        ),
      ),
      domain: 'variable_costs',
      role: 'intermediate',
      position: { x: 780, y: 640 },
    }),
    metric({
      id: 'net_loss_cost',
      name: 'Чистая стоимость потерь',
      description: 'Выбирает резерв или событийный факт по явному переключателю.',
      behavior: 'flow',
      unit: RUB,
      formula: formula(
        'if(use_event_loss_data ≥ 0.5, event_loss_cost, loss_reserve_cost)',
        conditional(
          compare('gte', ref('use_event_loss_data'), literal(0.5)),
          ref('event_loss_cost'),
          ref('loss_reserve_cost'),
        ),
      ),
      domain: 'variable_costs',
      role: 'intermediate',
      position: { x: 1140, y: 510 },
    }),
    metric({
      id: 'completed_cycles',
      name: 'Завершённые циклы',
      description: 'Эквивалентные циклы батарей за модельный период.',
      behavior: 'flow',
      unit: CYCLE,
      formula: formula('successful_rentals × cycles_per_rental', multiply(ref('successful_rentals'), ref('cycles_per_rental'))),
      domain: 'variable_costs',
      role: 'diagnostic',
      position: { x: 780, y: 770 },
    }),
    metric({
      id: 'equivalent_batteries_worn',
      name: 'Эквивалент износа батарей',
      description: 'Доля ресурса батарей, потреблённая за месяц.',
      behavior: 'flow',
      unit: POWERBANK,
      formula: formula('completed_cycles / useful_cycles_per_battery', divide(ref('completed_cycles'), ref('useful_cycles_per_battery'))),
      domain: 'variable_costs',
      role: 'diagnostic',
      position: { x: 1140, y: 770 },
    }),
    metric({
      id: 'battery_wear_cost',
      name: 'Износ батарей',
      description: 'Стоимость потреблённого ресурса батарей.',
      behavior: 'flow',
      unit: RUB,
      formula: formula('equivalent_batteries_worn × replacement_cost', multiply(ref('equivalent_batteries_worn'), ref('battery_replacement_cost'))),
      domain: 'variable_costs',
      role: 'intermediate',
      position: { x: 1500, y: 770 },
    }),

    input(
      'sim_cost',
      'SIM за месяц',
      'Ежемесячная связь одной станции.',
      'flow',
      RUB,
      100,
      'fixed_costs',
      'input',
      { x: 780, y: 930 },
      { min: 0, max: 3000, step: 50 },
    ),
    input(
      'maintenance_cost',
      'Обслуживание за месяц',
      'Ремонт и регулярное обслуживание станции.',
      'flow',
      RUB,
      500,
      'fixed_costs',
      'input',
      { x: 780, y: 1060 },
      { min: 0, max: 10000, step: 100 },
    ),
    input(
      'rebalancing_cost',
      'Ребалансировка за месяц',
      'Переменная логистика и перемещение батарей.',
      'flow',
      RUB,
      0,
      'variable_costs',
      'input',
      { x: 780, y: 1190 },
      { min: 0, max: 30000, step: 100 },
    ),
    input(
      'other_cash_opex',
      'Прочий OPEX за месяц',
      'Другие денежные расходы станции до налогов.',
      'flow',
      RUB,
      0,
      'fixed_costs',
      'input',
      { x: 780, y: 1320 },
      { min: 0, max: 30000, step: 100 },
    ),
    input(
      'station_purchase_cost',
      'Стоимость станции',
      'Закупочная стоимость станции без батарей.',
      'stock',
      RUB,
      4000,
      'capex',
      'input',
      { x: 780, y: 1450 },
      { min: 0, max: 100000, step: 500 },
      { grain: stationSnapshot },
    ),
    input(
      'delivery_cost',
      'Доставка',
      'Разовые затраты на доставку станции.',
      'stock',
      RUB,
      3000,
      'capex',
      'input',
      { x: 780, y: 1580 },
      { min: 0, max: 50000, step: 500 },
      { grain: stationSnapshot },
    ),
    input(
      'installation_cost',
      'Монтаж',
      'Разовые затраты на установку и ввод в эксплуатацию.',
      'stock',
      RUB,
      3000,
      'capex',
      'input',
      { x: 780, y: 1710 },
      { min: 0, max: 50000, step: 500 },
      { grain: stationSnapshot },
    ),
    input(
      'starter_inventory_cost',
      'Стартовый запас',
      'Дополнительный стартовый запас и аксессуары сверх батарей в станции.',
      'stock',
      RUB,
      0,
      'capex',
      'input',
      { x: 780, y: 1840 },
      { min: 0, max: 100000, step: 500 },
      { grain: stationSnapshot },
    ),
    input(
      'station_life_months',
      'Срок амортизации',
      'Срок линейной амортизации станции в месяцах.',
      'stock',
      MONTH,
      36,
      'capex',
      'input',
      { x: 780, y: 1970 },
      { min: 1, max: 120, step: 1, integer: true },
      { grain: stationSnapshot },
    ),

    metric({
      id: 'battery_capex',
      name: 'CAPEX батарей',
      description: 'Целое число батарей × закупочная стоимость.',
      behavior: 'stock',
      unit: RUB,
      grain: stationSnapshot,
      formula: formula('battery_count × battery_replacement_cost', multiply(ref('battery_count'), ref('battery_replacement_cost'))),
      domain: 'capex',
      role: 'intermediate',
      position: { x: 1140, y: 1430 },
    }),
    metric({
      id: 'total_capex',
      name: 'Итоговый CAPEX',
      description: 'Станция, батареи, доставка, монтаж и стартовый запас.',
      behavior: 'stock',
      unit: RUB,
      grain: stationSnapshot,
      formula: formula(
        'station + batteries + delivery + installation + starter inventory',
        sum([
          ref('station_purchase_cost'),
          ref('battery_capex'),
          ref('delivery_cost'),
          ref('installation_cost'),
          ref('starter_inventory_cost'),
        ]),
      ),
      domain: 'capex',
      role: 'output',
      position: { x: 1500, y: 1430 },
    }),
    metric({
      id: 'station_depreciation',
      name: 'Амортизация за месяц',
      description: 'Линейная амортизация CAPEX; не используется для расчёта payback.',
      behavior: 'flow',
      unit: RUB,
      formula: formula(
        'total_capex / station_life_months × 1 month',
        multiply(divide(ref('total_capex'), ref('station_life_months')), literal(1, MONTH)),
      ),
      domain: 'fixed_costs',
      role: 'intermediate',
      position: { x: 1860, y: 1430 },
    }),
    metric({
      id: 'total_cash_inflow',
      name: 'Общий денежный inflow',
      description: 'Арендная выручка плюс подтверждённые взыскания; состав показан раздельно.',
      behavior: 'flow',
      unit: RUB,
      formula: formula('rental_revenue + recovered_lost_charge', add(ref('rental_revenue'), ref('recovered_lost_charge'))),
      domain: 'revenue',
      role: 'output',
      position: { x: 1140, y: 100 },
    }),
    metric({
      id: 'cash_contribution',
      name: 'Денежный вклад станции',
      description: 'Деньги после всех денежных OPEX, но до CAPEX, амортизации и налогов.',
      behavior: 'flow',
      unit: RUB,
      formula: formula(
        'revenue − venue − acquiring − losses − wear − SIM − maintenance − rebalancing − other',
        subtract(
          ref('rental_revenue'),
          sum([
            ref('venue_commission'),
            ref('acquiring_cost'),
            ref('net_loss_cost'),
            ref('battery_wear_cost'),
            ref('sim_cost'),
            ref('maintenance_cost'),
            ref('rebalancing_cost'),
            ref('other_cash_opex'),
          ]),
        ),
      ),
      domain: 'results',
      role: 'output',
      position: { x: 1860, y: 360 },
    }),
    metric({
      id: 'profit_before_tax',
      name: 'Прибыль до налогов',
      description: 'Денежный вклад минус амортизация. Налоговая схема пока не задана.',
      behavior: 'flow',
      unit: RUB,
      formula: formula('cash_contribution − station_depreciation', subtract(ref('cash_contribution'), ref('station_depreciation'))),
      domain: 'results',
      role: 'north_star',
      position: { x: 2220, y: 360 },
    }),
    metric({
      id: 'payback_months',
      name: 'Срок окупаемости',
      description: 'CAPEX / положительный денежный вклад; амортизация не вычитается второй раз.',
      behavior: 'rate',
      unit: MONTH,
      formula: formula(
        'if(cash_contribution > 0, total_capex / cash_contribution × 1 month, 9999 months)',
        conditional(
          compare('gt', ref('cash_contribution'), literal(0)),
          multiply(divide(ref('total_capex'), ref('cash_contribution')), literal(1, MONTH)),
          literal(9999, MONTH),
        ),
      ),
      domain: 'results',
      role: 'guardrail',
      position: { x: 2220, y: 510 },
    }),
    metric({
      id: 'contribution_margin',
      name: 'Contribution margin',
      description: 'Денежный вклад как доля арендной выручки.',
      behavior: 'rate',
      unit: PERCENT,
      formula: formula(
        'if(revenue > 0, cash_contribution / revenue, 0)',
        conditional(
          compare('gt', ref('rental_revenue'), literal(0)),
          divide(ref('cash_contribution'), ref('rental_revenue')),
          literal(0),
        ),
      ),
      domain: 'results',
      role: 'diagnostic',
      position: { x: 2220, y: 660 },
    }),
  ];

  const metrics = Object.fromEntries(metricList.map((item) => [item.id, item]));

  return {
    schemaVersion: MODEL_SCHEMA_VERSION,
    id: 'tokberi-station-unit-economics',
    name: 'TokBeri — экономика станции',
    description: 'Детерминированная месячная модель одной станции. Франшиза, HQ и налоги исключены из Phase 1.',
    activeNorthStarId: 'profit_before_tax',
    metrics,
    scenarios: {
      base: {
        id: 'base',
        label: 'Base',
        description: 'Рабочая 6-слотовая станция, 1,5 аренды в день.',
        overrides: {},
      },
      weak: {
        id: 'weak',
        label: 'Weak',
        description: 'Слабая локация: 0,5 аренды в день.',
        overrides: { potential_demand: 0.7, rentals_per_day: 0.5 },
      },
      good: {
        id: 'good',
        label: 'Good',
        description: 'Хорошая локация: 4 аренды в день.',
        overrides: { potential_demand: 5, rentals_per_day: 4 },
      },
      hotspot: {
        id: 'hotspot',
        label: 'Hotspot',
        description: 'Высоконагруженная 8-слотовая станция.',
        overrides: {
          potential_demand: 12,
          rentals_per_day: 10,
          operational_capacity: 12,
          total_slots: 8,
          battery_count: 6,
          station_purchase_cost: 8000,
          maintenance_cost: 700,
          rebalancing_cost: 1000,
        },
      },
    },
    influenceRelations: [
      {
        id: 'potential-demand-to-rentals',
        from: 'potential_demand',
        to: 'rentals_per_day',
        type: 'influence',
        sign: 1,
        weight: 0.8,
        confidence: 'medium',
        source: 'Рабочая продуктовая гипотеза',
      },
    ],
  };
}
